table normalized_jobs
	lineageTag: e0db9a9f-39d8-4165-b30c-7f6ac912ffb5

	column job_id
		dataType: int64
		formatString: 0
		lineageTag: ee31c54b-aebc-4287-973b-375f9b28ae41
		summarizeBy: none
		sourceColumn: job_id

		annotation SummarizationSetBy = Automatic

	column company_name
		dataType: string
		lineageTag: 68899375-6e1a-48f9-a3a4-bd2e90387f35
		summarizeBy: none
		sourceColumn: company_name

		annotation SummarizationSetBy = Automatic

	column title
		dataType: string
		lineageTag: f165476d-c5bb-42a4-b3a1-e141af9a0bda
		summarizeBy: none
		sourceColumn: title

		annotation SummarizationSetBy = Automatic

	column description
		dataType: string
		lineageTag: 324fec72-1d9d-471e-a513-ff717f347615
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	column max_salary
		dataType: double
		lineageTag: f5950c3e-028f-4cf2-a1cb-e6680c0f2d8b
		summarizeBy: sum
		sourceColumn: max_salary

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pay_period
		dataType: string
		lineageTag: 198a4d6c-831f-40c5-9963-11974f690aea
		summarizeBy: none
		sourceColumn: pay_period

		annotation SummarizationSetBy = Automatic

	column location
		dataType: string
		lineageTag: af6f0f81-3f64-4b8a-adc5-363aeff3028c
		summarizeBy: none
		sourceColumn: location

		annotation SummarizationSetBy = Automatic

	column company_id
		dataType: int64
		formatString: 0
		lineageTag: 73a273ba-b30a-464f-9ad1-5961aa3ac7ba
		summarizeBy: sum
		sourceColumn: company_id

		annotation SummarizationSetBy = Automatic

	column views
		dataType: int64
		formatString: 0
		lineageTag: f54b90a2-5a47-46e4-804c-813f2bb0600a
		summarizeBy: sum
		sourceColumn: views

		annotation SummarizationSetBy = Automatic

	column med_salary
		dataType: int64
		formatString: 0
		lineageTag: 611327c3-c108-49c8-8436-6bbdc09dab7e
		summarizeBy: sum
		sourceColumn: med_salary

		annotation SummarizationSetBy = Automatic

	column min_salary
		dataType: double
		lineageTag: 73ff77e6-4821-4b7c-bd57-959eeb08db4b
		summarizeBy: sum
		sourceColumn: min_salary

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column formatted_work_type
		dataType: string
		lineageTag: 3fe7eca4-bb29-4f30-b6cd-7733395d4d8b
		summarizeBy: none
		sourceColumn: formatted_work_type

		annotation SummarizationSetBy = Automatic

	column applies
		dataType: int64
		formatString: 0
		lineageTag: 318d2391-e809-44cd-985d-581e718286dc
		summarizeBy: sum
		sourceColumn: applies

		annotation SummarizationSetBy = Automatic

	column original_listed_time
		dataType: int64
		formatString: 0
		lineageTag: 837e0f0b-3e8c-4600-a36d-a0c5a002add2
		summarizeBy: sum
		sourceColumn: original_listed_time

		annotation SummarizationSetBy = Automatic

	column remote_allowed
		dataType: int64
		formatString: 0
		lineageTag: 8d40492d-8f46-4581-8cff-baec6a8706d8
		summarizeBy: sum
		sourceColumn: remote_allowed

		annotation SummarizationSetBy = Automatic

	column job_posting_url
		dataType: string
		lineageTag: 1d754b78-336a-45f0-9fe4-78dc83a7c281
		summarizeBy: none
		sourceColumn: job_posting_url

		annotation SummarizationSetBy = Automatic

	column application_url
		dataType: string
		lineageTag: 2fb17a39-5874-44db-ac56-9a09aa5c808e
		summarizeBy: none
		sourceColumn: application_url

		annotation SummarizationSetBy = Automatic

	column application_type
		dataType: string
		lineageTag: df781897-f6e1-4c23-b414-ab43dc9088c4
		summarizeBy: none
		sourceColumn: application_type

		annotation SummarizationSetBy = Automatic

	column expiry
		dataType: int64
		formatString: 0
		lineageTag: 1525581b-3b49-4fef-8021-9dce2408175b
		summarizeBy: sum
		sourceColumn: expiry

		annotation SummarizationSetBy = Automatic

	column closed_time
		dataType: int64
		formatString: 0
		lineageTag: 12386620-639c-4efc-9cd4-4c243c0bdf1a
		summarizeBy: sum
		sourceColumn: closed_time

		annotation SummarizationSetBy = Automatic

	column formatted_experience_level
		dataType: string
		lineageTag: d6cd1448-2819-4c21-a6be-034ef2b1a080
		summarizeBy: none
		sourceColumn: formatted_experience_level

		annotation SummarizationSetBy = Automatic

	column skills_desc
		dataType: string
		lineageTag: c65886e3-f2c4-4a51-9e3b-45031362e245
		summarizeBy: none
		sourceColumn: skills_desc

		annotation SummarizationSetBy = Automatic

	column listed_time
		dataType: int64
		formatString: 0
		lineageTag: 5a78da56-2363-48cd-82c4-8cdb291eb7d4
		summarizeBy: sum
		sourceColumn: listed_time

		annotation SummarizationSetBy = Automatic

	column posting_domain
		dataType: string
		lineageTag: d5c01dce-874c-441d-b9ed-f979885f4c52
		summarizeBy: none
		sourceColumn: posting_domain

		annotation SummarizationSetBy = Automatic

	column sponsored
		dataType: int64
		formatString: 0
		lineageTag: fd85143e-3d20-4c7f-8f7c-15e7d0e2f5eb
		summarizeBy: sum
		sourceColumn: sponsored

		annotation SummarizationSetBy = Automatic

	column work_type
		dataType: string
		lineageTag: 3d3ff419-7c07-4012-87c8-4def1edef913
		summarizeBy: none
		sourceColumn: work_type

		annotation SummarizationSetBy = Automatic

	column currency
		dataType: string
		lineageTag: 83e2445d-28b2-41ee-b1a6-cf57d27de46f
		summarizeBy: none
		sourceColumn: currency

		annotation SummarizationSetBy = Automatic

	column compensation_type
		dataType: string
		lineageTag: c47e78d8-d1de-4114-96ec-f7afdb1082a2
		summarizeBy: none
		sourceColumn: compensation_type

		annotation SummarizationSetBy = Automatic

	column normalized_salary
		dataType: double
		lineageTag: eedf5ec1-40fd-42de-89e6-8fb5679ef7fb
		summarizeBy: sum
		sourceColumn: normalized_salary

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column zip_code
		dataType: int64
		formatString: 0
		lineageTag: dcb66cec-cbe5-4538-bee1-8614dc30ffb2
		summarizeBy: sum
		sourceColumn: zip_code

		annotation SummarizationSetBy = Automatic

	column fips
		dataType: int64
		formatString: 0
		lineageTag: c679a4f9-5e93-4822-8ca9-71e7089e4a1c
		summarizeBy: sum
		sourceColumn: fips

		annotation SummarizationSetBy = Automatic

	column technical_skills
		dataType: string
		lineageTag: 138f9698-f403-475a-8351-242302c817a8
		summarizeBy: none
		sourceColumn: technical_skills

		annotation SummarizationSetBy = Automatic

	column soft_skills
		dataType: string
		lineageTag: 15003fc7-0439-40c6-a365-81148f6a3775
		summarizeBy: none
		sourceColumn: soft_skills

		annotation SummarizationSetBy = Automatic

	column tools
		dataType: string
		lineageTag: b2a2a352-a5ea-4abd-a027-a96ed82d4245
		summarizeBy: none
		sourceColumn: tools

		annotation SummarizationSetBy = Automatic

	column certifications
		dataType: string
		lineageTag: d8784a18-2ada-4177-8796-46d86eec4e62
		summarizeBy: none
		sourceColumn: certifications

		annotation SummarizationSetBy = Automatic

	column experience
		dataType: string
		lineageTag: d63dfeb6-87a0-439a-a52b-d1ce11b1c11e
		summarizeBy: none
		sourceColumn: experience

		annotation SummarizationSetBy = Automatic

	column education
		dataType: string
		lineageTag: 40cc9953-757f-4e26-8a97-5c2656b01217
		summarizeBy: none
		sourceColumn: education

		annotation SummarizationSetBy = Automatic

	column annotator
		dataType: string
		lineageTag: 8822d7ed-16ac-4b87-ba74-b9ad411d3998
		summarizeBy: none
		sourceColumn: annotator

		annotation SummarizationSetBy = Automatic

	column review_status
		dataType: string
		lineageTag: 6c97fbad-438e-4b47-92bb-9377228c9f44
		summarizeBy: none
		sourceColumn: review_status

		annotation SummarizationSetBy = Automatic

	column comments
		dataType: string
		lineageTag: cc80b569-5759-4a1f-8ae4-92657a0a0daf
		summarizeBy: none
		sourceColumn: comments

		annotation SummarizationSetBy = Automatic

	column normalized_technical_skills
		dataType: string
		lineageTag: 5a5dada0-e5e8-4a71-bb3b-51956f9c7a1e
		summarizeBy: none
		sourceColumn: normalized_technical_skills

		annotation SummarizationSetBy = Automatic

	partition normalized_jobs = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\PGDBA 2nd sem sources\AI_Job_Posting_Analyzer\04_POWER_BI\Dataset\normalized_jobs.csv"),[Delimiter=",", Columns=41, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"job_id", Int64.Type}, {"company_name", type text}, {"title", type text}, {"description", type text}, {"max_salary", type number}, {"pay_period", type text}, {"location", type text}, {"company_id", Int64.Type}, {"views", Int64.Type}, {"med_salary", Int64.Type}, {"min_salary", type number}, {"formatted_work_type", type text}, {"applies", Int64.Type}, {"original_listed_time", Int64.Type}, {"remote_allowed", Int64.Type}, {"job_posting_url", type text}, {"application_url", type text}, {"application_type", type text}, {"expiry", Int64.Type}, {"closed_time", Int64.Type}, {"formatted_experience_level", type text}, {"skills_desc", type text}, {"listed_time", Int64.Type}, {"posting_domain", type text}, {"sponsored", Int64.Type}, {"work_type", type text}, {"currency", type text}, {"compensation_type", type text}, {"normalized_salary", type number}, {"zip_code", Int64.Type}, {"fips", Int64.Type}, {"technical_skills", type text}, {"soft_skills", type text}, {"tools", type text}, {"certifications", type text}, {"experience", type text}, {"education", type text}, {"annotator", type text}, {"review_status", type text}, {"comments", type text}, {"normalized_technical_skills", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

